Repository prgrms-web-devcourse/Team_Sagack_MonthSub_BE, pull requests merged in 2021-12, with the labels that each got.

#6 [MON-13] feat : 시리즈 모집공고 단건 조회 API 구현
  src/main/java/com/prgrms/monthsub/controller/SeriesController.java
  src/main/java/com/prgrms/monthsub/converter/ArticleConverter.java
  src/main/java/com/prgrms/monthsub/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/converter/UserConverter.java
  src/main/java/com/prgrms/monthsub/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/dto/response/BriefArticleBySeriesIdResponse.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesGetListResponse.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesOneResponse.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesOneWithUserResponse.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesOneWithWriterResponse.java
  src/main/java/com/prgrms/monthsub/repository/ArticleRepository.java
  src/main/java/com/prgrms/monthsub/repository/SeriesRepository.java
  src/main/java/com/prgrms/monthsub/service/SeriesService.java
Labels: 백엔드, 시리즈(모집공고)

#7 [MON-17] feat : 시리즈 모집공고 리스트 조회 API 구현
  src/main/java/com/prgrms/monthsub/controller/SeriesController.java
  src/main/java/com/prgrms/monthsub/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesGetListResponse.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesListResponse.java
  src/main/java/com/prgrms/monthsub/repository/SeriesRepository.java
  src/main/java/com/prgrms/monthsub/service/ArticleService.java
  src/main/java/com/prgrms/monthsub/service/SeriesService.java
Labels: 백엔드, 시리즈(모집공고)

#11 [MON-86] fix : 시리즈 조회 API 에러 수정
  src/main/java/com/prgrms/monthsub/dto/response/SeriesOneResponse.java
  src/main/java/com/prgrms/monthsub/repository/ArticleRepository.java
Labels: 백엔드, 버그

#10 [MON-49] feat : 인증 예외 처리
  src/main/java/com/prgrms/monthsub/common/config/SecurityConfig.java
  src/main/java/com/prgrms/monthsub/common/error/ApiResponse.java
  src/main/java/com/prgrms/monthsub/common/error/ErrorCode.java
  src/main/java/com/prgrms/monthsub/common/error/FilterExceptionHandler.java
  src/main/java/com/prgrms/monthsub/common/error/exception/UnAuthorizedException.java
  src/main/java/com/prgrms/monthsub/jwt/JwtAuthenticationFilter.java
Labels: 백엔드

#18 [MON-14] feat : 시리즈 수정 API 구현
  src/main/java/com/prgrms/monthsub/controller/SeriesController.java
  src/main/java/com/prgrms/monthsub/domain/Series.java
  src/main/java/com/prgrms/monthsub/dto/SeriesSubscribeEdit.java
  src/main/java/com/prgrms/monthsub/service/SeriesService.java
Labels: 리뷰 요청, 백엔드, 시리즈(모집공고)

#19 [MON-88] chore : 시리즈 수정/조회 API 코드 수정
  src/main/java/com/prgrms/monthsub/controller/SeriesController.java
  src/main/java/com/prgrms/monthsub/converter/ArticleConverter.java
  src/main/java/com/prgrms/monthsub/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/converter/UserConverter.java
  src/main/java/com/prgrms/monthsub/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/domain/Series.java
  src/main/java/com/prgrms/monthsub/dto/SeriesSubscribeList.java
  src/main/java/com/prgrms/monthsub/dto/SeriesSubscribeOne.java
  src/main/java/com/prgrms/monthsub/dto/response/BriefArticleBySeriesIdResponse.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesListResponse.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesOneWithUserResponse.java
  src/main/java/com/prgrms/monthsub/dto/response/SeriesOneWithWriterResponse.java
  src/main/java/com/prgrms/monthsub/service/SeriesService.java
Labels: 백엔드, 시리즈(모집공고)

#22 [MON-91] fix : CORS 에러 해결
  src/main/java/com/prgrms/monthsub/common/config/WebConfig.java
Labels: 버그

#23 [MON-92] chore : 시리즈 수정 API 리팩토링
  src/main/java/com/prgrms/monthsub/common/error/exception/domain/writer/WriterException.java
  src/main/java/com/prgrms/monthsub/controller/SeriesController.java
  src/main/java/com/prgrms/monthsub/dto/SeriesSubscribeEdit.java
  src/main/java/com/prgrms/monthsub/dto/SeriesSubscribeList.java
  src/main/java/com/prgrms/monthsub/dto/SeriesSubscribeOne.java
  src/main/java/com/prgrms/monthsub/repository/SeriesRepository.java
  src/main/java/com/prgrms/monthsub/service/SeriesService.java
  src/main/java/com/prgrms/monthsub/service/WriterService.java
Labels: 백엔드, 버그

#25 [MON-94] CORS 설정 YML로 관리
  src/main/java/com/prgrms/monthsub/common/config/JwtConfig.java
  src/main/java/com/prgrms/monthsub/common/config/OpenAPIConfig.java
  src/main/java/com/prgrms/monthsub/common/config/Security.java
  src/main/java/com/prgrms/monthsub/common/config/SecurityConfig.java
  src/main/java/com/prgrms/monthsub/common/config/WebConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 백엔드, 버그

#30 [MON-15] feat : 시리즈 좋아요 API 구현
  src/main/java/com/prgrms/monthsub/controller/SeriesLikesController.java
  src/main/java/com/prgrms/monthsub/domain/Series.java
  src/main/java/com/prgrms/monthsub/domain/SeriesLikes.java
  src/main/java/com/prgrms/monthsub/domain/enumType/LikesStatus.java
  src/main/java/com/prgrms/monthsub/dto/SeriesLikesEvent.java
  src/main/java/com/prgrms/monthsub/repository/SeriesLikesRepository.java
  src/main/java/com/prgrms/monthsub/service/SeriesLikesService.java
  src/main/java/com/prgrms/monthsub/service/SeriesService.java
Labels: 백엔드, 좋아요 기능

#35 [MON-118] chore : 좋아요 API 코드 수정
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesLikesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/domain/exception/SeriesException.java
Labels: 백엔드, 좋아요 기능

#44 [MON-69] feat : 내 채널 조회 API 구현
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesRepository.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/module/part/writer/domain/Writer.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesLikesRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesLikesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesUserRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesUserService.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MyChannelConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MyChannel.java
Labels: 백엔드, 채널

#49 [MON-127] feat: 다른 유저 채널 조회 API 구현
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesRepository.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MyChannelConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MyChannel.java
Labels: 백엔드, 채널

#56 [MON-123] chore : JPQL에서 Query 메서드로 리팩토링
  src/main/java/com/prgrms/monthsub/module/part/user/converter/UserConverter.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesRepository.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesService.java
  src/main/java/com/prgrms/monthsub/module/series/article/app/ArticleRepository.java
  src/main/java/com/prgrms/monthsub/module/series/article/app/ArticleService.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesLikesRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesLikesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesUserRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesUserService.java
Labels: 백엔드

#69 [MON-153] fix : 시리즈, 아티클 이미지 EDIT API CORS 에러 수정
  src/main/java/com/prgrms/monthsub/module/series/article/app/ArticleController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
Labels: 백엔드, 버그

#70 [MON-154] chore: 내 채널 조회 API response 수정
  src/main/java/com/prgrms/monthsub/module/part/writer/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MyChannel.java
Labels: 백엔드, 채널

#75 [MON-162] chore : 시리즈 리스트 조회 API Response 형식 수정
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesSubscribeList.java
  src/main/resources/application.yml
Labels: 백엔드, 시리즈(모집공고)

#80 [MON-172] feat: 랜딩 페이지(메인) 조회 API 구현
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MainPageAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MainPageController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MainPageConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MainPage.java
  src/main/resources/application.yml
Labels: 백엔드

#85 [MON-135] feat: 작가의 시리즈 발행 리스트 조회 API
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/provider/WriterProvider.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
Labels: 백엔드, 시리즈(모집공고)

#87 [MON-71] feat: 작가 Follow API 구현
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterController.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesRepository.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/domain/Writer.java
  src/main/java/com/prgrms/monthsub/module/part/writer/domain/WriterLikes.java
  src/main/java/com/prgrms/monthsub/module/part/writer/dto/WriterFollowEvent.java
Labels: 백엔드

#93 [MON-183] feat: 시리즈 카테고리 필터링 API
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/domain/Series.java
Labels: 백엔드

#99 [MON-202] fix: 시리즈 카테고리 필터링 API 버그 수정
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
Labels: 백엔드, 버그

#103 [MON-203] feat: 좋아요한 시리즈 리스트 상태값 추가
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesLikesRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesLikesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/domain/Series.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MyChannel.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesSubscribeList.java
Labels: 백엔드, 좋아요 기능

#109 [MON-216] feat: 시리즈 구독 테이블을 시리즈 결제 테이블로 병합 작업
  src/main/java/com/prgrms/monthsub/module/payment/app/PaymentRepository.java
  src/main/java/com/prgrms/monthsub/module/payment/app/PaymentService.java
  src/main/java/com/prgrms/monthsub/module/payment/app/provider/PaymentProvider.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesUserRepository.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesUserService.java
Labels: 백엔드

#113 [MON-221] feat: 시리즈 전체 조회 API, 좋아요 상태값 추가
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesRepositoryCustom.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesService.java
Labels: 백엔드

#114 Sprint4 Merge
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesRepositoryCustom.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesService.java
Labels: 백엔드

#117 [MON-223] feat: 채널 조회시 isMine, isFollowed 상태 값 추가
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterController.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesRepository.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelController.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MainPageConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MyChannelConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MainPage.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MyChannel.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesSubscribeList.java
Labels: 백엔드

#119 [MON-231] fix: 누락된 category 항목 추가
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MainPage.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MyChannel.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesSubscribeList.java
Labels: 백엔드, 버그

#126 [MON-224] feat: Scheduler로 시리즈 상태값 변경 및 정렬 구현
  src/main/java/com/prgrms/monthsub/MonthSubApplication.java
  src/main/java/com/prgrms/monthsub/common/scheduler/ScheduledHandler.java
  src/main/java/com/prgrms/monthsub/common/scheduler/Scheduler.java
  src/main/java/com/prgrms/monthsub/common/scheduler/config/SchedulerConfig.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MainPageConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/domain/Series.java
Labels: 백엔드

#130 [MON-237] fix: 메인 페이지 API 분리 작업
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterController.java
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterService.java
  src/main/java/com/prgrms/monthsub/module/part/writer/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/module/part/writer/dto/WriterLikesList.java
  src/main/java/com/prgrms/monthsub/module/part/writer/dto/WriterList.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MainPageAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MainPageController.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/SeriesController.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MainPageConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MainPage.java
  src/main/resources/application.yml
Labels: 백엔드

#133 [MON-218] fix: DTO class를 sealed와 record로 변경 작업
  src/main/java/com/prgrms/monthsub/module/part/user/converter/UserConverter.java
  src/main/java/com/prgrms/monthsub/module/part/user/dto/UserEdit.java
  src/main/java/com/prgrms/monthsub/module/part/user/dto/UserLogin.java
  src/main/java/com/prgrms/monthsub/module/part/user/dto/UserMe.java
  src/main/java/com/prgrms/monthsub/module/part/user/dto/UserSignUp.java
  src/main/java/com/prgrms/monthsub/module/part/writer/converter/WriterConverter.java
  src/main/java/com/prgrms/monthsub/module/part/writer/dto/WriterFollowEvent.java
  src/main/java/com/prgrms/monthsub/module/part/writer/dto/WriterLikesList.java
  src/main/java/com/prgrms/monthsub/module/part/writer/dto/WriterList.java
  src/main/java/com/prgrms/monthsub/module/payment/dto/PaymentPost.java
  src/main/java/com/prgrms/monthsub/module/payment/dto/PaymentSeries.java
  src/main/java/com/prgrms/monthsub/module/series/article/converter/ArticleConverter.java
  src/main/java/com/prgrms/monthsub/module/series/article/dto/ArticleEdit.java
  src/main/java/com/prgrms/monthsub/module/series/article/dto/ArticleOne.java
  src/main/java/com/prgrms/monthsub/module/series/article/dto/ArticlePost.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/MyChannel.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesLikesEvent.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesLikesList.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesSubscribeEdit.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesSubscribeList.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesSubscribeOne.java
  src/main/java/com/prgrms/monthsub/module/series/series/dto/SeriesSubscribePost.java
Labels: 백엔드

#136 [MON-241] fix: 비회원의 다른 유저 채널 방문 에러 수정
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelController.java
Labels: 백엔드, 버그
