Repository prgrms-web-devcourse/Team_Sagack_MonthSub_BE, pull requests merged in 2022-01, with the labels that each got.

#141 [MON-246] fix: 코드 리팩토링 작업
  src/main/java/com/prgrms/monthsub/common/scheduler/Scheduler.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MyChannelConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/SeriesConverter.java
  src/main/java/com/prgrms/monthsub/module/series/series/domain/Series.java
Labels: 백엔드

#152 [MON-274] fix: 채널 조회시 followingCount 에러 수정
  src/main/java/com/prgrms/monthsub/module/part/writer/app/WriterLikesService.java
  src/main/java/com/prgrms/monthsub/module/series/series/app/MyChannelAssemble.java
  src/main/java/com/prgrms/monthsub/module/series/series/converter/MyChannelConverter.java
Labels: 버그

#155 [MON-252] fix: 코드 리팩토링
  src/test/java/com/prgrms/monthsub/module/part/user/app/UserServiceTest.java
Labels: 테스트

#153 [MON-248] feat : 시리즈 ServiceLayer 테스트 구현
  src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
Labels: 시리즈(모집공고), 테스트
